/*
 * This source file was generated by the Gradle 'init' task
 */
package schilf;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting string");
    }

    @Test
    void appHasCorrectGreeting() {
        App classUnderTest = new App();
        assertEquals("Hello World, how are you today?", classUnderTest.getGreeting(),
                "app should have a greeting of \"\"Hello World, how are you today?\"");
    }

}
