/*
 * This source file was generated by the Gradle 'init' task
 */
package schilf;

public class App {
    public String getGreeting() {
        return "Hello World, how are you today?";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
